services:
  - type: web
    name: wcc-admin-backend
    env: node
    repo: https://github.com/rence141/west-coast-college-admin
    rootDir: admin
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://WestCoastCollegeAdmin:WCC26@cluster0.sm99qsu.mongodb.net/wcc-admin?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ3Y2MtMjg0NzU2IiwibmFtZSI6IkxvcmVuem8iLCJlbWFpbCI6ImxvcmVuem9Ad2VzdGNvYXN0LmVkdSIsImVudGl0bGVtZW50cyI6WyJzdHVkZW50IiwiZGV2ZWxvcGVyIl0sImRlcGFydG1lbnQiOiJDb21wdXRlciBTY2llbmNlIiwiaWF0IjoxNzA3NDE4OTk5LCJleHAiOjE3Mzg5NTQ5OTl9.Xp9_S7N_8_W1NlZqR1I6XzZ2RzZfTjU5XzFfTzY3XzIwcc-admin-production-secret
